export const FETCH_PHOTOS = "FETCH_PHOTOS";
export const AUTHOR_TYPED = "AUTHOR_TYPED";
export const PHOTO_SELECTED = "PHOTO_SELECTED";
export const PAGE_CHANGED = "PAGE_CHANGED";
export const PAGE_SIZE_CHANGED = "PAGE_SIZE_CHANGED";
export const LOVE_PHOTO = "LOVE_PHOTO";
